apiVersion: v1
kind: Service
metadata:
  name: gitbook
  labels:
    name: gitbook
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
  selector:
    name: gitbook