apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitbook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gitbook
    spec:
      containers:
      - name: operator
        image: upmcenterprises/gitbook
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /srv
            name: docs
      volumes:
        - name: docs
          gitRepo:
            repository: "https://github.com/stevesloka/gitbook.git"